version: '3.1'
services:
  linux:
    #build: ./ubuntu
    image: ubuntu-buildenv
    ports:
    - "2030:22"
    volumes:
    - /Users/jenkins/Desktop/installers/linux:/var/installers
    - /Users/jenkins/Desktop/artifacts:/var/artifacts
    restart: always
  windows:
    build: ./wine
    ports:
    - "2040:22"
    volumes:
    - /Users/jenkins/Desktop/installers/windows:/var/installers
    - /Users/jenkins/Desktop/artifacts:/var/artifacts
    restart: always 
  android:
    build: ./android
    ports:
    - "2050:22"
    volumes:
    - /Users/jenkins/Desktop/installers/linux:/var/installers
    - /Users/jenkins/Desktop/artifacts:/var/artifacts
    restart: always
