version: '3.1'
services:
  buildenv:
    build: ./ubuntu
    ports:
    - "2030:22"
    volumes:
    - /Users/jenkins/Desktop/installers/linux:/var/installers
    - /Users/jenkins/Desktop/artifacts:/var/artifacts
    restart: always
