Vagrant.configure("2") do |config|

  config.vm.box = "hashicorp/boot2docker"
  config.vm.allowed_synced_folder_types = [:rsync]
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.check_guest_additions = false
    v.functional_vboxsf = false
  end
  
  config.ssh.port = 2222
  config.ssh.insert_key = true
  config.ssh.username = 'docker'
  config.ssh.password = 'tcuser'
    
  # b2d doesnt support NFS
  config.nfs.functional = false  

  config.vm.network "forwarded_port", host: 2030, guest: 2030
  config.vm.network "public_network", ip: "192.168.2.220"

  # add default gateway:
  #config.vm.provision "shell", 
  #  run: "always", 
  #  inline: "route add default gw 192.168.2.1"
end
