Vagrant.configure("2") do |config|

  config.vm.box = "hashicorp/boot2docker"
  config.vm.allowed_synced_folder_types = [:rsync]
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.check_guest_additions = false
    v.functional_vboxsf = false
  end
  
  config.ssh.port = 2222
  config.ssh.insert_key = false
  config.ssh.username = 'docker'
  config.ssh.password = 'tcuser'
    
  # b2d doesnt support NFS
  config.nfs.functional = false  
end
